version: "3"
services:
  your-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
feature-security
      - "5432:5432"

# Security configuration
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true

    command: ["-b", "0.0.0.0"]
