version: "3"
services:
  your-service:
    image: cvmlundqvist/df
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"


# Security configuration
#  keycloak:
#    image: jboss/keycloak
#    env_file:
#      - .env
#    environment:
#      - PROXY_ADDRESS_FORWARDING=true
#    command: ["-b", "0.0.0.0"]
#    ports:
#      - "8081:8081"
