name: Docker Image CI - TidsbankenBE

on:
  push:
    branches:
      - main

env:
  APP_NAME: TidsbankenBE

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Tidsbanken
    steps:
      - uses: actions/checkout@v2
      - name: Debug environment variables
        run: echo "Username is ${{ secrets.DOCKERHUB_USERNAME }} and App name is $APP_NAME"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/$APP_NAME:latest

